ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--BB means bloodbank
CREATE TABLESPACE TS_BB
DATAFILE 'TS_BB.dbf'
SIZE 100m
AUTOEXTEND ON
NEXT 100m
MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
--create ADMIN user
CREATE USER BB_ADMIN IDENTIFIED BY qwerty
DEFAULT TABLESPACE TS_BB
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITEd ON TS_BB;
--grant privileges to ADMIN
GRANT ALL PRIVILEGES TO BB_ADMIN;
GRANT CREATE SESSION TO BB_ADMIN;
GRANT CREATE USER TO BB_ADMIN;
GRANT CREATE ANY DIRECTORY TO BB_ADMIN WITH ADMIN OPTION;
GRANT EXECUTE ON dbms_crypto TO BB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON dbms_xmldom TO BB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON dbms_xslprocessor TO BB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON dbms_xmlparser TO BB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON dbms_xmldom TO BB_ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON dbms_lob TO BB_ADMIN WITH GRANT OPTION;
--create CLIENT PROFILE
CREATE PROFILE PF_BBCLIENT LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;   
--create CLIENT
CREATE USER BB_CLIENT IDENTIFIED BY qwerty
DEFAULT TABLESPACE TS_BB
PROFILE PF_BBCLIENT
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITEd ON TS_BB;

--create role for CLIENT
CREATE ROLE RL_BB_CLIENT;
GRANT EXECUTE ON ADD_NEW_ACCOUNT TO RL_BB_CLIENT;
GRANT EXECUTE ON ADD_NEW_DONOR TO RL_BB_CLIENT;
GRANT EXECUTE ON ADD_NEW_TAKER TO RL_BB_CLIENT;
GRANT EXECUTE ON UPDATE_DONOR_INFO TO RL_BB_CLIENT;
GRANT EXECUTE ON UPDATE_TAKER_INFO TO RL_BB_CLIENT;
GRANT EXECUTE ON GETDONORS TO RL_BB_CLIENT;
GRANT EXECUTE ON GETTAKERS TO RL_BB_CLIENT;
GRANT EXECUTE ON GETBLOOD_BANKS TO RL_BB_CLIENT;
GRANT EXECUTE ON GETTRANSFER_DETAILS_FOR_CLIEN TO RL_BB_CLIENT;
GRANT EXECUTE ON FIND_DONORS_BY_BLOODGROUP TO RL_BB_CLIENT;
GRANT EXECUTE ON FIND_AVAIL_DONORS_BY_GR_ADDR TO RL_BB_CLIENT;
GRANT EXECUTE ON FIND_UNAVAIL_DONORS_BY_GR_ADDR TO RL_BB_CLIENT;
GRANT EXECUTE ON GET_BLOOD_LEADER TO RL_BB_CLIENT;
GRANT EXECUTE ON TOTAL_BLOOD_TRANSFER TO RL_BB_CLIENT;
GRANT EXECUTE ON NOTAL_NO TO RL_BB_CLIENT;
GRANT EXECUTE ON BLOOD_TRANSFERS_VOLUME_ON_DATE TO RL_BB_CLIENT;
commit;

--grant role to CLIENT
GRANT RL_BB_CLIENT TO BB_CLIENT;