//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOOD_BANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BLOOD_BANK()
        {
            this.TRANSFER_DETAILS = new HashSet<TRANSFER_DETAILS>();
        }
    
        public string BLOODBANK_ID { get; set; }
        public string BLOODBANK_NAME { get; set; }
        public string BLOOD_GROUP { get; set; }
        public Nullable<decimal> BLOOD_AMOUNT { get; set; }
        public string BLOOD_STATUS { get; set; }
        public Nullable<System.DateTime> CHECKING_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFER_DETAILS> TRANSFER_DETAILS { get; set; }
    }
}
