//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFER_DETAILS
    {
        public decimal TRANSER_ID { get; set; }
        public string BLOODBANK_ID { get; set; }
        public Nullable<decimal> DONOR_ID { get; set; }
        public Nullable<decimal> TAKER_ID { get; set; }
        public string BLOOD_GROUP { get; set; }
        public Nullable<decimal> BLOOD_AMOUNT { get; set; }
        public Nullable<System.DateTime> TRANSFER_DATE { get; set; }
    
        public virtual BLOOD_BANK BLOOD_BANK { get; set; }
        public virtual DONOR DONOR { get; set; }
        public virtual TAKER TAKER { get; set; }
    }
}
